name: Daily YouTube Scraping

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 11 * * *'
    - cron: '30 15 * * *'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
   scrape-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Install Chrome for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Run scraping script
      env:
        # Add your environment variables here
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        # Add any other environment variables your script needs
      run: |
        # Set Puppeteer to use the installed Chrome
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
        node main-scrap.js
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add scrapped_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped data [skip ci]" && git push) 
